<?php

/*
+-----------------------------------------------------------------------+
| language/es_ES/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['disablemotd'] = 'No mostrar esta página de nuevo';
$labels['motd'] = 'Mensaje del día';

?>
